/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export interface Post {
  'id' : Time,
  'content' : ExternalBlob,
  'likes' : bigint,
  'timestamp' : Time,
  'caption' : string,
  'comments' : Array<Comment>,
}
export interface Story { 'content' : ExternalBlob, 'timestamp' : Time }
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'profilePicture' : Uint8Array,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commentOnPost' : ActorMethod<[Principal, Time, string], undefined>,
  'createPost' : ActorMethod<[ExternalBlob, string], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExplorePosts' : ActorMethod<[bigint], Array<Post>>,
  'getFollowedUsersStories' : ActorMethod<[], Array<[Principal, Array<Story>]>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getUserFeed' : ActorMethod<[], Array<Post>>,
  'getUserPosts' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[Principal, Time], undefined>,
  'postStory' : ActorMethod<[ExternalBlob], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];